### ISSUE TITLE
Schematic for Feather Form Factor

### ISSUE THREAD

**Issue by sai-ydev** [blues/note-hardware#1]
Hello,

You have shared the design files for the feather notecard carrier. May I ask you to upload the schematic in pdf format? I don't have the requisite software to open the design files.

**Comment by bsatrom** [comment]
Thanks for the suggestion @sai-ydev! We'll create PDF exports and add that to the repo.

**Comment by jwiedey** [comment]
https://github.com/blues/note-hardware/blob/master/Notecarrier-AF/v1.7/Sources/Schematic.PDF

**Comment by sai-ydev** [comment]
👍🏽 Thanks!
