### ISSUE TITLE
No `NOTE-WBNAN`

### ISSUE THREAD

**Issue by daterdots** [blues/note-hardware#24]
I don't see the model of my notecard in the [folder](https://github.com/blues/note-hardware/tree/master/Notecard) of Notecard 3D files and drawings. 

![notecard](https://github.com/user-attachments/assets/1569fdc6-f08c-401b-a468-c3845cbab322)

**Comment by bsatrom** [comment]
Hey @daterdots Just added it: https://github.com/blues/note-hardware/blob/master/Notecard/NOTE-WBNAN%20drawing%20v3.2.PDF
