### ISSUE TITLE
M.2 connector part number in BOM for the Notecarrier-Pi is incorrect

### ISSUE THREAD

**Issue by nicksinas** [blues/note-hardware#8]
Part Number for the M.2 in the BOM is: MDT420E01001  
This is an M.2 Key A part from Amphenol:
![image](https://user-images.githubusercontent.com/6588089/198126351-670822b7-74b8-4555-86d8-cc8d8c6071e3.png)

The Notecarrier-Pi has an M.2 Key E part:
![image](https://user-images.githubusercontent.com/6588089/198126468-47205544-b5e3-41f1-a748-c75970d850ad.png)
![image](https://user-images.githubusercontent.com/6588089/198126489-d412798c-13c3-456f-80a5-5246162c34a3.png)

M.2 Connector Types:  
![image](https://user-images.githubusercontent.com/6588089/198126609-18057e87-227f-4d03-9bdb-a98135044275.png)

So what is the correct part number?

**Comment by nicksinas** [comment]
Eh this may be my mistake. Based on the callout in that drawing, I think the part number is actually correct, the drawing was just misleading.  
![image](https://user-images.githubusercontent.com/6588089/198128444-33922d76-aa1e-443f-ad64-6d648502a4ed.png)
  
My mistake!

**Comment by nicksinas** [comment]
Also the DigiKey picture didn't help either haha  
![image](https://user-images.githubusercontent.com/6588089/198128705-0b26a300-a20b-444f-a372-4bc4f36aeee0.png)

**Comment by jwiedey** [comment]
I was just typing an explanation, along with a warning that Digi-Key/Mouser have confusing pictures!
As you already figured out, the "E" in the part number is for the key, and the part number in the BOM is correct.
